export const TRANSACTION_TYPES = [
    { "id": "", "name": "Seçilmedi" },
    { "id": "0", "name": "Kullanılmayan Tür" },
    { "id": "1", "name": "Çekim Talebi" },
    { "id": "2", "name": "Çekim talebi Ödemesi" },
    { "id": "3", "name": "Yatırım" },
    { "id": "4", "name": "Müşteriye Ödeme" },
    { "id": "5", "name": "Kasa Depozitosu" },
    { "id": "6", "name": "Yatırım Talebi" },
    { "id": "7", "name": "Yatırım Talebi Ödemesi" },
    { "id": "8", "name": "Çekim Talebi Reddedilmiştir" },
    { "id": "9", "name": "Müşteri Talep İptali" },
    { "id": "10", "name": "Bahis" },
    { "id": "11", "name": "Düzeltme Alt" },
    { "id": "14", "name": "Bahis Nakit Çıkışı" },
    { "id": "15", "name": "Kazanç Artar" },
    { "id": "16", "name": "Kazanç Düşer" },
    { "id": "17", "name": "Kaybedilen Bahis" },
    { "id": "18", "name": "Bahis hesaplanmadı" },
    { "id": "19", "name": "Temsilcinin Kaybedilen Bahsi" },
    { "id": "20", "name": "Bahis İadesi" },
    { "id": "21", "name": "Rollback Winning" },
    { "id": "22", "name": "Temsilciden Temsilciye Transferi" },
    { "id": "23", "name": "Temsilciden Oyuncuya Transferi" },
    { "id": "24", "name": "Partner Limiti Düzeltme" },
    { "id": "25", "name": "Mevduat İadesi" },
    { "id": "26", "name": "Kasa Devir Limitinin Düzeltilmesi" },
    { "id": "27", "name": "Para Çekmenin İadesi" },
    { "id": "30", "name": "Kasadan Geçişe Transfer" },
    { "id": "31", "name": "Ana Kasadan Geçişe Transfer" },
    { "id": "32", "name": "Betshopun Ana Ofise Transferi" },
    { "id": "33", "name": "Ana Ofisten Kasa Transferi" },
    { "id": "34", "name": "Kasadan Kasaya Transfer" },
    { "id": "35", "name": "Kasadan Bahislerin Ödenmesi" },
    { "id": "36", "name": "Kasa Diğer Gelirler" },
    { "id": "37", "name": "Kasa Diğer Masraf" },
    { "id": "38", "name": "Kasa Düzeltme Üst" },
    { "id": "39", "name": "Kasa Düzeltme Alt" },
    { "id": "40", "name": "Bet İndirim" },
    { "id": "41", "name": "Bahis Tazminatı" },
    { "id": "50", "name": "Canlı Krupiye Bahşişi" },
    { "id": "51", "name": "Ana Ofise transfer" },
    { "id": "52", "name": "Kasa Transfer Limiti" },
    { "id": "54", "name": "CashDesk Commision" },
    { "id": "55", "name": "Cashdesk Deposit Payment" },
    { "id": "56", "name": "Terminal QR Deposit" },
    { "id": "57", "name": "Terminal QR Withdraw" },
    { "id": "70", "name": "Partner Cloud Bank Düzeltme Üst" },
    { "id": "71", "name": "Partner Cloud Bank Düzeltme Alt" },
    { "id": "80", "name": "Sadakat Puanı Değişimi" },
    { "id": "81", "name": "Paranın Bloke Edilmesi" },
    { "id": "82", "name": "Müşteri Bonusunun İptali" },
    { "id": "83", "name": "Müşteri Bonusunun Ödemesi" },
    { "id": "84", "name": "Cashback Bonusu" },
    { "id": "85", "name": "Bonus Para Üst" },
    { "id": "86", "name": "Bonus Para Alt" },
    { "id": "87", "name": "Casino Slot Cashback Bonusu" },
    { "id": "88", "name": "FirstAPI Freeze Money" },
    { "id": "90", "name": "Sanal Slot Bahis Kazanması" },
    { "id": "95", "name": "Jackpot Kazanma" },
    { "id": "96", "name": "Tournament Win" },
    { "id": "101", "name": "Bahisten Gelir" },
    { "id": "102", "name": "Diğer Gelirler" },
    { "id": "103", "name": "Vezneye Nakit girişi" },
    { "id": "104", "name": "Kartlardan nakit girişi" },
    { "id": "106", "name": "Borç ödemelerinden nakit" },
    { "id": "108", "name": "Internet Müşterilerinden Gelir" },
    { "id": "109", "name": "% 10'dan Gelir" },
    { "id": "110", "name": "Müşteriden Gelir" },
    { "id": "111", "name": "Kurucudan Gelir" },
    { "id": "114", "name": "Reklamdan Gelir" },
    { "id": "120", "name": "Mevduat Geliri" },
    { "id": "122", "name": "İnternetten Gelen Gelirler" },
    { "id": "123", "name": "Bankadan Gelir (Kasa, Diğer)" },
    { "id": "124", "name": "Bankadan Ana Ofise Gelir" },
    { "id": "125", "name": "Borçlu" },
    { "id": "126", "name": "İnşaat" },
    { "id": "127", "name": "Nakliye" },
    { "id": "128", "name": "Reklam" },
    { "id": "129", "name": "Expo" },
    { "id": "130", "name": "Nork Akıl Hastanesi İnşaatından Elde Edilen Gelir" },
    { "id": "131", "name": "Casino" },
    { "id": "132", "name": "Sanal" },
    { "id": "133", "name": "Vivaro Grubu" },
    { "id": "134", "name": "Vivaro" },
    { "id": "135", "name": "BetConstruct" },
    { "id": "136", "name": "Banka Hesabından Çıktı" },
    { "id": "137", "name": "Canlı Casino" },
    { "id": "138", "name": "Aştarak Otoyol Ofisleri" },
    { "id": "139", "name": "Aştarak Bölgesi İnşaatı" },
    { "id": "140", "name": "Kafkasya Kompleksi İnşaatı" },
    { "id": "141", "name": "\"Smart City\" CJSC" },
    { "id": "150", "name": "Temsilciden Müşteriye Kredi Üst" },
    { "id": "151", "name": "Temsilciden Müşteriye Kredi Alt" },
    { "id": "152", "name": "Temsilciden Temsilciye Kredi Üst" },
    { "id": "153", "name": "Temsilciden Temsilciye Kredi Alt" },
    { "id": "154", "name": "Temsilci Kredisinin Artırılması" },
    { "id": "155", "name": "Temsilci Kredisinin Azaltılması" },
    { "id": "156", "name": "Temsilci Düzeltmesi" },
    { "id": "157", "name": "Temsilci Müşteri Depozitosu" },
    { "id": "158", "name": "Temsilci Müşteri Para Çekme" },
    { "id": "180", "name": "Temsilci Tarafından Müşteri Depozitosu" },
    { "id": "200", "name": "Müşteri Depozito Talebinin Reddi" },
    { "id": "201", "name": "Vezneden Nakit çıkışı" },
    { "id": "202", "name": "Diğer Sonuçlar" },
    { "id": "204", "name": "Kart için Sonuç" },
    { "id": "208", "name": "İnternet Müşterilerine Sonuç" },
    { "id": "209", "name": "Yüzde için Sonuç" },
    { "id": "210", "name": "Müşteri İçin Sonuç" },
    { "id": "211", "name": "Kurucu için Sonuç" },
    { "id": "213", "name": "Ücret için Sonuç" },
    { "id": "214", "name": "Reklam için Sonuç" },
    { "id": "215", "name": "Bahis Kuponu Baskı Sonucu" },
    { "id": "216", "name": "Bahis Mağazası Kira Sonucu" },
    { "id": "220", "name": "Para yatırma sonucu" },
    { "id": "222", "name": "Vergiler için Sonuç" },
    { "id": "232", "name": "Oyun için Diğer Sonuç" },
    { "id": "233", "name": "Oyun Ücreti İçin Sonuç" },
    { "id": "234", "name": "Oyun Reklamı İçin Sonuç" },
    { "id": "240", "name": "Borçlu" },
    { "id": "245", "name": "Banka Sonucu (Diğer)" },
    { "id": "246", "name": "Ana Ofisten Bankaya Masraf" },
    { "id": "247", "name": "İnşaat" },
    { "id": "248", "name": "Nakliye" },
    { "id": "249", "name": "Reklam" },
    { "id": "250", "name": "Expo" },
    { "id": "251", "name": "Nork Akıl Hastanesi İnşaatı İçin Çıktı" },
    { "id": "252", "name": "Casino" },
    { "id": "253", "name": "Sanal" },
    { "id": "254", "name": "Vivaro Grubu" },
    { "id": "255", "name": "Vivaro" },
    { "id": "256", "name": "BetConstruct" },
    { "id": "257", "name": "Banka hesabına gelir" },
    { "id": "258", "name": "Canlı Casino" },
    { "id": "259", "name": "Aştarak Otoyol Ofisleri" },
    { "id": "260", "name": "Aştarak Bölgesi İnşaatı" },
    { "id": "261", "name": "Kafkasya Kompleksi İnşaatı" },
    { "id": "262", "name": "\"Smart City\" CJSC" },
    { "id": "263", "name": "Soft City" },
    { "id": "301", "name": "Düzeltim Yukarı" },
    { "id": "302", "name": "Düzeltim Aşağı" },
    { "id": "303", "name": "Bonus Düzeltimi" },
    { "id": "304", "name": "Cüzdanından Cüzdana Transfer" },
    { "id": "305", "name": "Spor Cüzdanından Casino Cüzdanına Transfer" },
    { "id": "306", "name": "Casino Cüzdanından Spor Cüzdanına Transfer" },
    { "id": "307", "name": "Gerçek Paradan Bonusa Transfer" },
    { "id": "308", "name": "Bonustan Gerçek Paraya Transfer" },
    { "id": "309", "name": "CashBack Düzeltmesi" },
    { "id": "310", "name": "Buddy'dan Buddy'ya Transferi" },
    { "id": "311", "name": "Para Çekme İptalinin Düzeltilmesi" },
    { "id": "312", "name": "Para Yatırma Cashback Bonusu" },
    { "id": "313", "name": "Para Yatırma Düzetlmesi" },
    { "id": "314", "name": "Negatif Bakiye Düzeltme" },
    { "id": "315", "name": "Casino Düzeltme Üst" },
    { "id": "316", "name": "Casino Düzeltme Alt" },
    { "id": "317", "name": "Client Witholding Tax" },
    { "id": "318", "name": "FreeBet Convert" },
    { "id": "501", "name": "Bağlılık Puanı Düzeltme Üst" },
    { "id": "502", "name": "Bağlılık Puanı Düzeltme Alt" },
    { "id": "503", "name": "Mağazada Satın Alma" },
    { "id": "504", "name": "Bağlılık Puanı Ödülü" },
    { "id": "505", "name": "Loyalty Item Purchas eCancel" },
    { "id": "601", "name": "Kasaya Nakit Girişi" },
    { "id": "602", "name": "Kasadan Nakit Çıkışı" },
    { "id": "603", "name": "Kasa Kapanışı" },
    { "id": "604", "name": "Kasa Cashbacki" },
    { "id": "605", "name": "Kasa Hesabı Düzeltme" },
    { "id": "701", "name": "Terminal Para Yatırma" },
    { "id": "702", "name": "Terminal Para Çekme" },
    { "id": "703", "name": "Terminal Makbuzundan Giriş" },
    { "id": "704", "name": "Terminal Makbuzundan Çıkış" },
    { "id": "705", "name": "Terminal Money CashIn" },
    { "id": "706", "name": "Nihai Nakit Çıkışı" },
    { "id": "707", "name": "Terminal Deposit From CashDesk" },
    { "id": "708", "name": "Terminal Money Card Cash In" },
    { "id": "709", "name": "Terminal Client Deposit Document" },
    { "id": "800", "name": "Bahsin Talep Edilmesi" },
    { "id": "801", "name": "Kazanılan Bahislerin Geri Alınması" },
    { "id": "802", "name": "Kazanılan Bahis Kazancının Geri Alınması" },
    { "id": "803", "name": "Bahis Kazancının Artışını Talep Edin" },
    { "id": "804", "name": "Kazanılan Bahislerin İadesi" },
    { "id": "805", "name": "Alınan Kazancın İade Edilmesi" },
    { "id": "810", "name": "Üye Önerme Primi Ödemesi" },
    { "id": "811", "name": "Arkadaşa Öner Bonusu Ödemesi" },
    { "id": "900", "name": "Promosyon Bonusu" },
    { "id": "912", "name": "Bahsi onayla" },
    { "id": "913", "name": "Cüzdana transfer" },
    { "id": "914", "name": "Cüzdandan Transfer" },
    { "id": "915", "name": "BuyRewardBundle" },
    { "id": "950", "name": "YoBuy" },
    { "id": "951", "name": "YoWin" }
];
